ã
8

NoOp"serve*1.10.02b'v1.10.0-rc1-19-g656e7a2b34'G

init_all_tablesNoOp
(
legacy_init_opNoOp^init_all_tables""$
legacy_init_op

legacy_init_op*·
predict«
%
keepProb
dropoutKeepProb:0
*
inputX 
inputX:0ÿÿÿÿÿÿÿÿÿ:
binaryPreds+
output/binaryPreds:0ÿÿÿÿÿÿÿÿÿtensorflow/serving/predict